In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
df = pd.read_csv('./titanic/train.csv')

In [3]:
# (1) 결측값 처림 : 처리한 결과를 기존 데이터 프레임에 저장

In [4]:
df.keys()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [5]:
df.shape

(891, 12)

In [6]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [7]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [10]:
# Age 결측치 처리
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Embarked 결측치 처리
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [11]:
df['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [12]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

(2) 레이블 인코딩: 기존 데이터 프레임을 새로은 데이터 프레임으로 저장한 다음 처리한 결과를 기존 데이터 컬럼은 삭제하고 새로운 데이터 프레임에 재저장
- Sex
- Embarked

In [14]:
from sklearn.preprocessing import LabelEncoder

# 1. 기존 데이터프레임을 새로운 데이터프레임으로 복사하여 저장
df_encoded = df.copy()

# 2. 레이블 인코더 생성
le = LabelEncoder()

# 3. Sex, Embarked 처리
# 처리 결과를 새로운 컬럼으로 저장한 후 기존 컬럼 삭제
for col in ['Sex', 'Embarked']:
    new_col_name = col + '_encoded'
    df_encoded[new_col_name] = le.fit_transform(df_encoded[col])
    
    # 기존 데이터 컬럼 삭제
    df_encoded.drop(col, axis=1, inplace=True)
    
    # 처리된 결과를 다시 기존 컬럼명으로 변경 (재저장)
    df_encoded.rename(columns={new_col_name: col}, inplace=True)

# 4. 결과 확인
df_encoded.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,1,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,0,2
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,1,2

(3) 원핫인코딩: 기존 데이터 프레임을 새로은 데이터 프레임으로 저장한 다음 처리한 결과를 기존 데이터 컬럼은 삭제하고 원핫인코더로 변환한 내용을 새로운 데이터 프레임에 추가할때 컬럼명은 적당히 정해서 추가한다.
- Sex: 
- Embarked

In [15]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

# 1. 기존 데이터프레임(df_encoded)을 새로운 데이터프레임(df_new)으로 복사
df_new = df_encoded.copy()

# 2. 원-핫 인코딩할 컬럼 정의 (데이터셋의 실제 컬럼명인 대문자로 수정)
target_cols = ['Sex', 'Embarked']

# 3. OneHotEncoder 설정
# sparse_output=False로 설정하면 .toarray()를 호출한 것과 같은 밀집 행렬을 반환합니다.
# dtype=int를 추가하여 0과 1로 나오게 설정합니다.
enc = OneHotEncoder(sparse_output=False, dtype=int)

for col in target_cols:
    # 원-핫 인코딩 적용 (2차원 구조로 입력해야 하므로 [[col]] 사용)
    encoded_data = enc.fit_transform(df_new[[col]])
    
    # 새로운 컬럼명 생성 (예: Sex_0, Sex_1 / Embarked_0, Embarked_1, Embarked_2)
    column_names = [f"{col}_{cat}" for cat in enc.categories_[0]]
    
    # 인코딩된 결과를 데이터프레임으로 변환하여 병합
    encoded_df = pd.DataFrame(encoded_data, columns=column_names, index=df_new.index)
    df_new = pd.concat([df_new, encoded_df], axis=1)
    
    # 기존 원본 컬럼 삭제
    df_new.drop(col, axis=1, inplace=True)

# 4. 결과 확인
print("변환 후 컬럼 리스트:", df_new.columns.tolist())
df_new.head()

변환 후 컬럼 리스트: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Sex_0', 'Sex_1', 'Embarked_0', 'Embarked_1', 'Embarked_2']

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_0,Sex_1,Embarked_0,Embarked_1,Embarked_2
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,0,1,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,1,0,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,0,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,1,0,0,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,0,1,0,0,1