In [1]:
import pandas as pd

s1 = pd.Series([0, 1], index=['A', 'B'])
s1

A    0
B    1
dtype: int64

In [2]:
s2 = pd.Series([2,3,4], index=['A','B','C'])
s2

A    2
B    3
C    4
dtype: int64

In [3]:
s3 = pd.concat([s1,s2]) # concat는 단순 연결이라서 인덱스를 새롭게 설정하는 작업인 reset_index가 필요하다.
s3

A    0
B    1
A    2
B    3
C    4
dtype: int64

In [4]:
s3 = pd.concat([s1, s2], axis=1)
s3

     0  1
A  0.0  2
B  1.0  3
C  NaN  4

In [5]:
import numpy as np
df1 = pd.DataFrame(np.arange(6).reshape(3,2),                # arange는 파이선이 제공하는 rang와 같다 # 6 이전까지의 숫자
                  index=['a','b','c'],                       # reshapge(3,2) 3행 2열 구조로 바꿔라!
                  columns=['데이터1','데이터2'])
df1

   데이터1  데이터2
a     0     1
b     2     3
c     4     5

In [6]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2,2),
                  index=['a','c'],
                  columns=['데이터3','데이터4'])
df2

   데이터3  데이터4
a     5     6
c     7     8

In [7]:
df3 = pd.concat([df1, df2], axis=1) # axis = 1 인 경우 
df3

   데이터1  데이터2  데이터3  데이터4
a     0     1   5.0   6.0
b     2     3   NaN   NaN
c     4     5   7.0   8.0

In [8]:
df3 = pd.concat([df1, df2], axis=0) # axis = 0 인 경우 
df3

   데이터1  데이터2  데이터3  데이터4
a   0.0   1.0   NaN   NaN
b   2.0   3.0   NaN   NaN
c   4.0   5.0   NaN   NaN
a   NaN   NaN   5.0   6.0
c   NaN   NaN   7.0   8.0

In [9]:
# join

df1 = pd.DataFrame([[1., 2.],[3., 4.], [5., 6.]],
                  index = ['a', 'c', 'e'],
                  columns=['서울', '부산'])
df1

    서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [10]:
df2 = pd.DataFrame([[7., 8.],[9., 10.],[11., 12.],[13, 14]],
                  index=['b','c','d','e'],
                  columns=['대구','광주'])
df2

     대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [11]:
# join 같은 경우에는 index를 기준으로 병합한다.

df3 = df1.join(df2, how='outer') # 기준이 없으면 index를 기준으로 병합한다.
df3

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [12]:
df4 = df1.join(df2, how='inner') # 기준이 없으면 index를 기준으로 병합한다.
df4

    서울   부산    대구    광주
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0

In [13]:
df5 = df1.join(df2, how='left')
df5

    서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
c  3.0  4.0   9.0  10.0
e  5.0  6.0  13.0  14.0

In [14]:
import numpy as np

n = np.nan
idx = ['row1', 'row2', 'row3']
col = ['col1', 'col2', 'col3']
data=[[1,2,200],[100,5,6],[7,300,n]]
df = pd.DataFrame(data, idx, col)
df

      col1  col2   col3
row1     1     2  200.0
row2   100     5    6.0
row3     7   300    NaN

In [15]:
# 최대값이 포함되어 있는 행 또는 열을 구하는데 사용하는 idxmax # 결측값을 제외하고 계산되어 진다.

# 만약 결측값을 포함시키고 싶으면 df.idxmin(axis=0, skipna=True)의 디폴트 값에서 df.idxmin(axis=0, skipna=False) 를 주면 된다.

df.idxmax(axis=0) 
# axis가 0 이기에 행값을 구한다.

col1    row2
col2    row3
col3    row1
dtype: str

In [16]:
df.idxmax(axis=1)

row1    col3
row2    col1
row3    col2
dtype: str

In [17]:
df.idxmin(axis=0)

col1    row1
col2    row1
col3    row2
dtype: str

In [18]:
df.idxmin(axis=1)

row1    col1
row2    col2
row3    col1
dtype: str

# 시계열 데이타 # 시계열 데이터 # To Data

In [19]:
date_str = ['2018, 1, 1', '2018, 1, 4', '2018, 1, 5'] 
idx = pd.to_datetime(date_str)
idx

DatetimeIndex(['2018-01-01', '2018-01-04', '2018-01-05'], dtype='datetime64[us]', freq=None)

In [20]:
np.random.seed(0)
s = pd.Series(np.random.randn(3), index=idx)
s

2018-01-01    1.764052
2018-01-04    0.400157
2018-01-05    0.978738
dtype: float64

In [21]:
pd.date_range('2020-7-1','2020-7-30') # date_range 는 범위를 표시해주는 함수 # freq = D는 Day의 의미
# 실제로 date_range가 많이 쓰인다.

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30'],
              dtype='datetime64[us]', freq='D')

In [22]:
pd.date_range(start='2020-7-1', end='2020-7-30') # 시작일과 마지막일을 사용

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
               '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
               '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
               '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
               '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
               '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
               '2020-07-29', '2020-07-30'],
              dtype='datetime64[us]', freq='D')

In [23]:
pd.date_range(start='2020-7-1', periods = 7) # 시작일과 기간을 사용

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06', '2020-07-07'],
              dtype='datetime64[us]', freq='D')

In [24]:
pd.date_range(start='2020-7-1', periods = 7, freq ='s')  # 초단위로 변경해서 출력함

DatetimeIndex(['2020-07-01 00:00:00', '2020-07-01 00:00:01',
               '2020-07-01 00:00:02', '2020-07-01 00:00:03',
               '2020-07-01 00:00:04', '2020-07-01 00:00:05',
               '2020-07-01 00:00:06'],
              dtype='datetime64[us]', freq='s')

In [25]:
pd.date_range('2026-1-1', '2026-12-31', freq='W') # 주 단위 # 주 단위를 설정하지 않으면 W-SUN 이 디폴트이다.

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08', '2026-02-15', '2026-02-22',
               '2026-03-01', '2026-03-08', '2026-03-15', '2026-03-22',
               '2026-03-29', '2026-04-05', '2026-04-12', '2026-04-19',
               '2026-04-26', '2026-05-03', '2026-05-10', '2026-05-17',
               '2026-05-24', '2026-05-31', '2026-06-07', '2026-06-14',
               '2026-06-21', '2026-06-28', '2026-07-05', '2026-07-12',
               '2026-07-19', '2026-07-26', '2026-08-02', '2026-08-09',
               '2026-08-16', '2026-08-23', '2026-08-30', '2026-09-06',
               '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04',
               '2026-10-11', '2026-10-18', '2026-10-25', '2026-11-01',
               '2026-11-08', '2026-11-15', '2026-11-22', '2026-11-29',
               '2026-12-06', '2026-12-13', '2026-12-20', '2026-12-27'],
              dtype='datetime64[us]', freq='W-SUN')

In [26]:
pd.date_range('2026-1-1', '2026-12-31', freq='W-MON') # 월요일 기준으로 함

DatetimeIndex(['2026-01-05', '2026-01-12', '2026-01-19', '2026-01-26',
               '2026-02-02', '2026-02-09', '2026-02-16', '2026-02-23',
               '2026-03-02', '2026-03-09', '2026-03-16', '2026-03-23',
               '2026-03-30', '2026-04-06', '2026-04-13', '2026-04-20',
               '2026-04-27', '2026-05-04', '2026-05-11', '2026-05-18',
               '2026-05-25', '2026-06-01', '2026-06-08', '2026-06-15',
               '2026-06-22', '2026-06-29', '2026-07-06', '2026-07-13',
               '2026-07-20', '2026-07-27', '2026-08-03', '2026-08-10',
               '2026-08-17', '2026-08-24', '2026-08-31', '2026-09-07',
               '2026-09-14', '2026-09-21', '2026-09-28', '2026-10-05',
               '2026-10-12', '2026-10-19', '2026-10-26', '2026-11-02',
               '2026-11-09', '2026-11-16', '2026-11-23', '2026-11-30',
               '2026-12-07', '2026-12-14', '2026-12-21', '2026-12-28'],
              dtype='datetime64[us]', freq='W-MON')

In [27]:
pd.date_range('2026-1-1', '2026-12-31', freq='W-FRI') # 금요일 기준으로 함

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06', '2026-02-13', '2026-02-20',
               '2026-02-27', '2026-03-06', '2026-03-13', '2026-03-20',
               '2026-03-27', '2026-04-03', '2026-04-10', '2026-04-17',
               '2026-04-24', '2026-05-01', '2026-05-08', '2026-05-15',
               '2026-05-22', '2026-05-29', '2026-06-05', '2026-06-12',
               '2026-06-19', '2026-06-26', '2026-07-03', '2026-07-10',
               '2026-07-17', '2026-07-24', '2026-07-31', '2026-08-07',
               '2026-08-14', '2026-08-21', '2026-08-28', '2026-09-04',
               '2026-09-11', '2026-09-18', '2026-09-25', '2026-10-02',
               '2026-10-09', '2026-10-16', '2026-10-23', '2026-10-30',
               '2026-11-06', '2026-11-13', '2026-11-20', '2026-11-27',
               '2026-12-04', '2026-12-11', '2026-12-18', '2026-12-25'],
              dtype='datetime64[us]', freq='W-FRI')

In [28]:
pd.date_range('2026-1-1', '2026-12-31', freq="B") # 평일을 의미한다.

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-06',
               '2026-01-07', '2026-01-08', '2026-01-09', '2026-01-12',
               '2026-01-13', '2026-01-14',
               ...
               '2026-12-18', '2026-12-21', '2026-12-22', '2026-12-23',
               '2026-12-24', '2026-12-25', '2026-12-28', '2026-12-29',
               '2026-12-30', '2026-12-31'],
              dtype='datetime64[us]', length=261, freq='B')

In [29]:
pd.date_range('2021-1-1','2021-12-31', freq='MS')

DatetimeIndex(['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01',
               '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01',
               '2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01'],
              dtype='datetime64[us]', freq='MS')

In [30]:
pd.date_range('2021-1-1','2021-12-31', freq='ME')

DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31'],
              dtype='datetime64[us]', freq='ME')

In [31]:
pd.date_range('2021-1-1','2021-12-31', freq='WOM-2SUN')

DatetimeIndex(['2021-01-10', '2021-02-14', '2021-03-14', '2021-04-11',
               '2021-05-09', '2021-06-13', '2021-07-11', '2021-08-08',
               '2021-09-12', '2021-10-10', '2021-11-14', '2021-12-12'],
              dtype='datetime64[us]', freq='WOM-2SUN')

In [32]:
pd.date_range('2021-1-1','2021-12-31', freq='QE-JAN')

DatetimeIndex(['2021-01-31', '2021-04-30', '2021-07-31', '2021-10-31'], dtype='datetime64[us]', freq='QE-JAN')

In [33]:
# kaggle #  데이터 저장소

# 예제 파일

In [34]:
sample1 = pd.read_csv('sample1.csv') # read_csv(파일 이름)
sample1

# sample1 파일을 그냥 불러옴

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [35]:
sample2 = pd.read_csv('sample2.csv', names=['c1','c2','c3'])
sample2

# sample2 의 컬럼 네임을 c1c2c3로 지정해줌

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [36]:
sample1 = pd.read_csv('sample1.csv', index_col='c1') # index col을 c1으로 지정
sample1

# index 컬럼을 c1으로 지정해서 c1 에 인덱스 컬럼으로 표시되게 함

      c2      c3
c1
1   1.11     one
2   2.22     two
3   3.33   three

In [37]:
sample3 = pd.read_table('sample3.txt', sep='\t') 
sample3

# 현재 파일은 탭 키를 기준으로 구분되어 있어서 백슬레시로 구분함 
# table, csv 둘 다 사용해도 불러 올 수 있음

         C1        C2        C3       C4
0  0.179181 -1.538472  1.347553  0.43381
1  1.024209  0.087307 -1.281997  0.49265
2  0.417899 -2.002308  0.255245 -1.10515

In [38]:
sample4 = pd.read_csv('sample4.txt', skiprows=[0,1]) # skiprows = [스킾할 행 기술]
sample4

# sample4를 보면 0번째 행과 1번째 행에 불필요한 데이터가 있다 이를 skip하기 위해
# skiprows를 사용해서 0, 1 번 인덱스를 선택해서 skip 했다.

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [39]:
# 파일에 누락으로 뜨는 데이터를 nan으로 처리하라는 뜻 : na_values=['누락']
# sample5 에 있는 '누락' 이라는 데이터를 Nan으로 처리해서 결과 값을 보면 Nan으로 뜨게 된다.

sample5 = pd.read_csv('sample5.csv', na_values=['누락'])
sample5

    c1    c2      c3
0  1.0  1.11     one
1  2.0   NaN     two
2  NaN  3.33   three

In [40]:
df = pd.read_csv('sample5.csv', na_values=['누락'])
df.to_csv('sample6.csv') # 아무것도 해주지 않으면 index header가 True로 설정된다.

In [41]:
df.to_csv('sample7.txt', sep='|')
# 구분자가 , 가 아닌 경우 txt 형태로 사용하는 경우가 많다.

In [42]:
df.to_csv('sample8.txt', na_rep='없음')
# nan 데이터를 na_rep ='' 안의 값에 명칭으로 불러온다는 의미이다.

In [43]:
df.to_csv('sample9.txt', index=False, header=True)
# 일반적으로 많이 쓰는 스타일로 index = F , header = T /// 공백은 nan이라는 뜻이다.
# nan (공백) 위치에 어떤 값을 넣고 싶으면 위의 sample8처럼 na_rep를 사용하면 된다.

In [44]:
df.index = ['a', 'b', 'c']
df.to_csv('sample10.csv', index=True, header=False)

#header는 false이기 때문에 따로 출력되지 않았다.

# 통계 함수

In [45]:
[N,T,F]=[np.nan,True,False]
df
idx = [['IDX1','IDX1','IDX2','IDX2'],['row1','row2','row3','row4']]
col = [['COL1','COL1','COL2','COL2'],['val1','val2','val3','val4']]
data = [[N,13,3,4],[5,7,10,8],[15,6,N,3],[2,14,9,1]]
df = pd.DataFrame(data,idx,col)
df

           COL1       COL2
           val1 val2  val3 val4
IDX1 row1   NaN   13   3.0    4
     row2   5.0    7  10.0    8
IDX2 row3  15.0    6   NaN    3
     row4   2.0   14   9.0    1

In [46]:
# 최대값 구하는 법

df.max(axis=0) # 명시적으로 언급하지 않으면 axis = 0

COL1  val1    15.0
      val2    14.0
COL2  val3    10.0
      val4     8.0
dtype: float64

In [47]:
df.max(axis=1)

IDX1  row1    13.0
      row2    10.0
IDX2  row3    15.0
      row4    14.0
dtype: float64

In [48]:
df.max(skipna=True)

COL1  val1    15.0
      val2    14.0
COL2  val3    10.0
      val4     8.0
dtype: float64

In [49]:
df.max(skipna=False)

COL1  val1     NaN
      val2    14.0
COL2  val3     NaN
      val4     8.0
dtype: float64

In [50]:
df.min(skipna=False)

COL1  val1    NaN
      val2    6.0
COL2  val3    NaN
      val4    1.0
dtype: float64

In [51]:
# 평균을 의미한다.     # 2차원 구조는 어느 방향성이 있어야 하는데 여기서도 axis의 디폴트는 0이다.

df.mean(axis=0)

COL1  val1     7.333333
      val2    10.000000
COL2  val3     7.333333
      val4     4.000000
dtype: float64

In [52]:
# 중앙값을 의미한다.
df.median(axis=0)

COL1  val1     5.0
      val2    10.0
COL2  val3     9.0
      val4     3.5
dtype: float64

In [53]:
# 최빈값

df.mode(axis=0)

   COL1       COL2
   val1 val2  val3 val4
0   2.0    6   3.0    1
1   5.0    7   9.0    3
2  15.0   13  10.0    4
3   NaN   14   NaN    8

In [54]:
# 표준편차

df.std(axis=0)

COL1  val1    6.806859
      val2    4.082483
COL2  val3    3.785939
      val4    2.943920
dtype: float64

In [55]:
# 분산

df.var(axis=0)

COL1  val1    46.333333
      val2    16.666667
COL2  val3    14.333333
      val4     8.666667
dtype: float64

In [56]:
col1 = [1,2,3,4,5,6]
col2 = [1,4,2,8,16,32]
col3 = [6,5,4,3,2,1]
data = {'col1':col1, 'col2':col2, 'col3':col3}
df = pd.DataFrame(data)
df

   col1  col2  col3
0     1     1     6
1     2     4     5
2     3     2     4
3     4     8     3
4     5    16     2
5     6    32     1

In [57]:
df.corr(method='pearson') # 상관관계 계수를 계산하는 것

          col1      col2      col3
col1  1.000000  0.887739 -1.000000
col2  0.887739  1.000000 -0.887739
col3 -1.000000 -0.887739  1.000000

In [58]:
df.corr(method='pearson', numeric_only = True) # numeric_only= True를 사용하면 문자를 제외한 숫자의 데이터만 선택할 수 있다.

          col1      col2      col3
col1  1.000000  0.887739 -1.000000
col2  0.887739  1.000000 -0.887739
col3 -1.000000 -0.887739  1.000000

In [59]:
import pandas as pd
import numpy as np

# 데이터 플레임을 정렬한느 기준 크게 2가지
# 인덱스를 기준
# 특정 컬럼 기준

df = pd.read_csv('./titanic/train.csv')
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [60]:
#행 인덱스를 기준으로 정리 / 내림차순으로 정렬 (ascending)
df.sort_index(ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [61]:
# Pclass 를 기준으로 정렬한다는 의미이다.

df.sort_values(by='Pclass', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C

In [62]:
# 피봇 pivot

data = {
    "도시": ["서울", "서울", "서울", "부산", "부산", "부산", "인천", "인천"],
    "연도": ["2015", "2010", "2005", "2015", "2010", "2005", "2015", "2010"],
    "인구": [9904312, 9631482, 9762546, 3448737, 3393191, 3512547, 2890451, 2632035],
    "지역": ["수도권", "수도권", "수도권", "경상권", "경상권", "경상권", "수도권", "수도권"]
}
columns = ['도시', '연도', '인구', '지역']
df1 = pd.DataFrame(data, columns=columns)
df1

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010  2632035  수도권

In [64]:
# index, column, value 의 순서대로 피봇 함수 () 안에 들어가게 된다.
# pivot 할 때 인덱스, 컬럼, 벨류를 다 지정해줘야한다.

df2 = df1.pivot(index="도시",columns="연도",values="인구") 
df2

연도       2005       2010       2015
도시
부산  3512547.0  3393191.0  3448737.0
서울  9762546.0  9631482.0  9904312.0
인천        NaN  2632035.0  2890451.0

In [65]:
# df1.pivot(index='지역', columns='연도', values='인구')

# duplicate entries 목록이 하나만 나와야한느데 여러개 나온 것 .....????
# 문법적으로 하자가 있는 것은 아니다, 중복되는 값이 나오다보니 오류가 나는 것이다.

ValueError: Index contains duplicate entries, cannot reshape

### pivot_table
형식) pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, margins_name='All')
- data: 분석할 데이터프레임 (메서드일 때는 필요하지 않음)
- values: 분석할 데이터프레임에서 분석할 열
- index: 행 인덱스로 들어갈 키 열 또는 키 열의 리스트
- columns: 열 인덱스로 들어갈 키 열 또는 키 열의 리스트
- aggfunc: 분석 메서드 지정
- fill_value: NaN 대체 값 설정
- margins: 오른쪽과 아래에 합계를 붙일지 여부 지정
- margins_name: 합계 열(행)의 이름 지정

In [66]:
df2 = pd.DataFrame({'key1':['A','A','B','B','A'],
                   'key2' : ['one','two','one', 'two', 'one'],
                   'data1':[1,2,3,4,5],
                   'data2':[10,20,30,40,50]})
df2

  key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [67]:
#                데이타,  인덱스, 컬럼
df2.pivot_table('data1','key1','key2')

# aggfunc='mean' 현재 디폴트이다.
# 여기서 집계함수가 빠져있다. # 여기서는 디폴드 값으로 평균을 집계함수로 사용하고 있다.

key2  one  two
key1
A     3.0  2.0
B     3.0  4.0

In [70]:
# 위에랑 똑같다.
df2.pivot_table('data1','key1','key2', aggfunc='sum')

key2  one  two
key1
A       6    2
B       3    4

In [71]:
# 위에랑 똑같다.
df2.pivot_table('data1','key1','key2', aggfunc=sum)

key2  one  two
key1
A       6    2
B       3    4

In [72]:
# margins 비벗 테이블의 총 합계 평균 # 근데 디폴트가 all 로 나타나서 잘 알 수가 없다.

df2.pivot_table('data1', 'key1', 'key2', margins=True)

key2  one  two       All
key1
A     3.0  2.0  2.666667
B     3.0  4.0  3.500000
All   3.0  3.0  3.000000

In [74]:
# margin은 총계의 평균의 의미, 여기서 디폴트가 all이라 헷갈리지 않게 
# margins_name = "평균"으로 잡아준다.

df2.pivot_table('data1', 'key1', 'key2', margins=True, margins_name='평균')

key2  one  two        평균
key1
A     3.0  2.0  2.666667
B     3.0  4.0  3.500000
평균    3.0  3.0  3.000000

In [75]:
# key1, key2를 기준으로 하위 그룹을 묶어 값을의 평균을 구한다.
df2.pivot_table('data1', index=['key1','key2'])

           data1
key1 key2
A    one     3.0
     two     2.0
B    one     3.0
     two     4.0

### 추가 라이브러리
- pip install matplotlib   / 시각화를 위한 도구
- pip install seaborn      / 시각화를 위한 도구
- pip install scipy

In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.family']='Malgun Gothic' # 글꼴을 맑은 고딕을 사용하겠다는 의미
plt.rcParams['axes.unicode_minus']=False # 마이너스 부호가 깨지는 현상을 막아줌

In [91]:
np.random.seed(0)
df1 = pd.DataFrame(np.random.randn(100, 3), # 100행 3열
                  index=pd.date_range('1/1/2018', periods=100),
                  columns=['A','B','C']).cumsum() # cumsum은 누적합의 의미이다.
df1.tail(3)

                    A          B          C
2018-04-08   9.605047   9.887789 -12.886190
2018-04-09   9.469097  11.024680 -12.788465
2018-04-10  10.052051  10.625231 -12.418409

In [92]:
df = pd.DataFrame({'col1':[1,-2,5,3,-1,7], 'col2':[3,4,np.nan,9,2,5]})
df

   col1  col2
0     1   3.0
1    -2   4.0
2     5   NaN
3     3   9.0
4    -1   2.0
5     7   5.0

In [93]:
df.cumsum() # nan은 제외되고 누적합이 계산된다.

# nan을 포함시키고 싶으면 df.cumsum(skipna=False)를 사용하면 된다.

   col1  col2
0     1   3.0
1    -1   7.0
2     4   NaN
3     7  16.0
4     6  18.0
5    13  23.0

In [94]:
df.cumsum(skipna=False)

# nan을 포함하는 순간 연산이 되지 않아 전부 nan이 된다.

   col1  col2
0     1   3.0
1    -1   7.0
2     4   NaN
3     7   NaN
4     6   NaN
5    13   NaN

# 시각화