# 문제 1
###### (1) 데이터프레임에서 037730 종목의 등락률을 출력하세요.
###### (2) 데이터프레임에서 iloc 속성을 사용하여 첫번째, 두번째 행을 슬라이싱하세요.
###### (3) 데이터프레임에서 loc 속성을 사용하여 첫번째, 두번째 행을 슬라이싱하세요.
###### (4) 데이터프레임에서 iloc 속성을 사용하여 첫 번째 컬럼을 인덱싱하세요.
###### (5) 데이터프레임에서 iloc 속성을 사용하여 '037730' 종목의 '종목명', '현재가' 컬럼을 선택하세요.
###### (6) 데이터프레임에서 현재가가 1500 이상인 값만 가져와보세요.
###### (7) 데이터프레임에서 현재가가 1,500원 이상이면서 1,700원 미만인 값만 필터링 해보세요.

In [1]:
import pandas as pd
import numpy as np

data = [
    ["037730", "3R", 1510, 7.36],
    ["036360", "3SOFT", 1790, 1.65],
    ["005760", "ACTS", 1185, 1.28],
]
columns = ["종목코드", "종목명", "현재가", "등락률"]
df = pd.DataFrame(data=data, columns=columns)
df.set_index('종목코드', inplace=True)

df

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
005760   ACTS  1185  1.28

In [2]:
# (1) 데이터프레임에서 037730 종목의 등락률을 출력하세요.

df1 = df.loc['037730', '등락률']
print(float(df1))
df1

7.36

np.float64(7.36)

In [3]:
# (2) 데이터프레임에서 iloc 속성을 사용하여 첫번째, 두번째 행을 슬라이싱하세요.

df2 = df.iloc[[0,1]] # df2 = df.iloc[0:2]
df2

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

In [4]:
# (3) 데이터프레임에서 loc 속성을 사용하여 첫번째, 두번째 행을 슬라이싱하세요.

df3 = df.loc[['037730','036360']] # df3 = df.loc['037730' : '036360'] # 라벨인덱스
df3

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

In [5]:
# (4) 데이터프레임에서 iloc 속성을 사용하여 첫 번째 컬럼을 인덱싱하세요.

df4 = df.iloc[:,0] # iloc [행, 열]
df4

종목코드
037730       3R
036360    3SOFT
005760     ACTS
Name: 종목명, dtype: str

In [6]:
# (5) 데이터프레임에서 iloc 속성을 사용하여 '037730' 종목의 '종목명', 
#'현재가' 컬럼을 선택하세요.

df5 = df.iloc[0,0:2]
df5

종목명      3R
현재가    1510
Name: 037730, dtype: object

In [7]:
# (6) 데이터프레임에서 현재가가 1500 이상인 값만 가져와보세요.

df6 = df.loc[df['현재가']>=1500]
df6

          종목명   현재가   등락률
종목코드
037730     3R  1510  7.36
036360  3SOFT  1790  1.65

In [8]:
# (7) 데이터프레임에서 현재가가 1,500원 이상이면서 1,700원 미만인 값만 필터링 해보세요.

df7 = df.loc[df['현재가']>=1500]
df8 = df.loc[df['현재가']<1700]

result = pd.merge(df7, df8) # inner join
result

  종목명   현재가   등락률
0  3R  1510  7.36

# 문제2 아래 코드를 활용해서 주어진 문제에 대한 코드를 작성하시오.

###### (1) 데이터프레임에서 테마별 PER, PBR의 평균을 계산하세요.
###### (2) 데이터프레임에서 테마별 종목의 개수를 계산하세요.
###### (3) 데이터프레임에서 테마별 PER의 평균을 계산하세요.
###### (4) 데이터프레임에 대해 테마로 그룹화한 후 PER, PBR 컬럼을 슬라이싱하세요. 그 다음 두 컬럼에 대한 평균을 계산하세요.
###### (5) 데이터프레임에 대해서 '테마' 컬럼으로 그룹화한 후 PER 컬럼은 max, PBR 컬럼은 min 함수를 적용해보세요.

In [9]:
data = [
    ["2차전지(생산)", "SK이노베이션", 10.19, 1.29],
    ["해운", "팬오션", 21.23, 0.95],
    ["시스템반도체", "티엘아이", 35.97, 1.12],
    ["해운", "HMM", 21.52, 3.20],
    ["시스템반도체", "아이에이", 37.32, 3.55],
    ["2차전지(생산)", "LG화학", 83.06, 3.75]
]

columns = ["테마", "종목명", "PER", "PBR"]
df = pd.DataFrame(data=data, columns=columns)
df

         테마      종목명    PER   PBR
0  2차전지(생산)  SK이노베이션  10.19  1.29
1        해운      팬오션  21.23  0.95
2    시스템반도체     티엘아이  35.97  1.12
3        해운      HMM  21.52  3.20
4    시스템반도체     아이에이  37.32  3.55
5  2차전지(생산)     LG화학  83.06  3.75

In [10]:
# (1) 데이터프레임에서 테마별 PER, PBR의 평균을 계산하세요.

df.rolling(window=6).mean(numeric_only=True)

         PER   PBR
0        NaN   NaN
1        NaN   NaN
2        NaN   NaN
3        NaN   NaN
4        NaN   NaN
5  34.881667  2.31

In [11]:
# (2) 데이터프레임에서 테마별 종목의 개수를 계산하세요. / size()함수를 이용해서 셀 수도 있다.

df.groupby('테마').count()

          종목명  PER  PBR
테마
2차전지(생산)    2    2    2
시스템반도체      2    2    2
해운          2    2    2

In [12]:
# (3) 데이터프레임에서 테마별 PER의 평균을 계산하세요.

df.groupby('테마')[['PER']].mean(numeric_only=True)

             PER
테마
2차전지(생산)  46.625
시스템반도체    36.645
해운        21.375

In [13]:
# (4) 데이터프레임에 대해 테마로 그룹화한 후 PER, PBR 컬럼을 슬라이싱하세요. 
# 그 다음 두 컬럼에 대한 평균을 계산하세요.

df.groupby('테마').mean(numeric_only=True)

             PER    PBR
테마
2차전지(생산)  46.625  2.520
시스템반도체    36.645  2.335
해운        21.375  2.075

In [14]:
# (5) 데이터프레임에 대해서 '테마' 컬럼으로 그룹화한 후
# PER 컬럼은 max, PBR 컬럼은 min 함수를 적용해보세요.



df1 = df.groupby('테마')[['PER']].max(numeric_only=True)
df2 = df.groupby('테마')[['PBR']].min(numeric_only=True)

result = pd.merge(df1, df2, left_index=True, right_index=True) 
result

            PER   PBR
테마
2차전지(생산)  83.06  1.29
시스템반도체    37.32  1.12
해운        21.52  0.95

# [문제3] 아래 코드를 활용해서 주어진 문제에 대한 코드를 작성하시오.
###### (1) df1과 df2를 'ID'라는 컬럼명을 기준으로 'inner' 방식으로 병합하세요.
###### (2) df1과 df2를 'ID’라는 컬럼명을 기준으로 ‘outer’ 방식으로 병합하세요.
###### (3) 데이터프레임에서 df1의 'ID'와 df2의 '아이디' 컬럼을 기준으로 merge 하세요.(아래 코드 참조)
######    df2 = pd.DataFrame(data=data2, columns=['아이디', '종목명'])

In [15]:
import pandas as pd

data1 = {
    'ID': [100, 101, 102, 103],
    'Name': ['Brayden', 'Clara', 'Ella', 'Oliver']
}

data2 = [
    [100, "삼성전자"],
    [100, "LG전자"],
    [101, "카카오"],
    [101, "NAVER"],
    [101, "현대차"]
]

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data=data2, columns=['ID', '종목명'])

df1

    ID     Name
0  100  Brayden
1  101    Clara
2  102     Ella
3  103   Oliver

In [16]:
df2

    ID    종목명
0  100   삼성전자
1  100   LG전자
2  101    카카오
3  101  NAVER
4  101    현대차

In [17]:
# (1) df1과 df2를 'ID'라는 컬럼명을 기준으로 'inner' 방식으로 병합하세요.

result_1 = pd.merge(df1, df2, on='ID')
result_1

    ID     Name    종목명
0  100  Brayden   삼성전자
1  100  Brayden   LG전자
2  101    Clara    카카오
3  101    Clara  NAVER
4  101    Clara    현대차

In [18]:
# (2) df1과 df2를 'ID’라는 컬럼명을 기준으로 ‘outer’ 방식으로 병합하세요.

result_2 = pd.merge(df1, df2, on='ID', how='outer')
result_2

    ID     Name    종목명
0  100  Brayden   삼성전자
1  100  Brayden   LG전자
2  101    Clara    카카오
3  101    Clara  NAVER
4  101    Clara    현대차
5  102     Ella    NaN
6  103   Oliver    NaN

In [19]:
# (3) 데이터프레임에서 df1의 'ID'와 df2의 '아이디' 컬럼을 기준으로 merge 하세요.
df2 = pd.DataFrame(data=data2, columns=['아이디', '종목명'])

result_3 = pd.merge(df1, df2, left_on='ID', right_on='아이디')
result_3

    ID     Name  아이디    종목명
0  100  Brayden  100   삼성전자
1  100  Brayden  100   LG전자
2  101    Clara  101    카카오
3  101    Clara  101  NAVER
4  101    Clara  101    현대차

# [문제4] 다음 데이터프레임에서 df1, df2의 인덱스를 기준으로 merge 하는 코드를 작성하시오.

In [20]:
import pandas as pd

data1 = {
    'ID': [100, 101, 102, 103],
    'Name': ['Brayden', 'Clara', 'Ella', 'Oliver']
}
data2 = [
    [100, "삼성전자"],
    [100, "LG전자"],
    [101, "카카오"],
    [101, "NAVER"],
    [101, "현대차"]
]

df1 = pd.DataFrame(data1)
df1.set_index('ID', inplace=True)
df2 = pd.DataFrame(data=data2, columns=['ID', '종목명'])
df2.set_index('ID', inplace=True)

In [21]:
df1

        Name
ID
100  Brayden
101    Clara
102     Ella
103   Oliver

In [22]:
df2

       종목명
ID
100   삼성전자
100   LG전자
101    카카오
101  NAVER
101    현대차

In [23]:
result_1 = pd.merge(df1, df2, on='ID', how='outer')
result_2 = pd.merge(df1, df2, on='ID', how='inner')
print(result_1)
print(result_2)

        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차
102     Ella    NaN
103   Oliver    NaN
        Name    종목명
ID
100  Brayden   삼성전자
100  Brayden   LG전자
101    Clara    카카오
101    Clara  NAVER
101    Clara    현대차